### PR TITLE
Support secrets with JSON values; update to Vault 0.10.3

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
This PR adds support for secrets that are objects, instead of just strings. So a `secrets.json` file could be like:

```json
{
  "secret/foo/bar": "baz",
  "secret/something/else": {
    "someKey": "someValue",
    "anotherKey": "anotherValue"
  }
}
```

And both will work. The latter produces output like:

```bash
$ VAULT_ADDR=http://localhost:8200 VAULT_TOKEN=root vault read secret/something/else
Key                  Value
---                  -----
refresh_interval     768h
someKey              someValue
anotherKey           anotherValue
```

Building with this `Dockerfile` today will update the public image to use the current latest version of Vault, 0.10.3. A [breaking change](https://stackoverflow.com/a/49903604/223225) was introduced in the Vault API in 0.10; to choose whether to use the old or new API, an environment variable is added to this image. Assuming you store secrets under `/secret`, set the environment variable as `VAULT_USE_V1_API=secret` to use the old API for `/secret`.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
It’s `VAULT_USE_V1_API=secret` (see the README) because you can’t enable the old API across all paths, you need to explicitly opt-in to ones where you want it enabled. Assuming most people use the path `/secret` as their default, I suggested `VAULT_USE_V1_API=secret`. Having this be the default mode for the image, though, might be problematic as the image would behave differently for paths under `/secret` versus anything else. Maybe `/secret` is so universally used that this isn’t a concern?

**Comment by bkeroackdsc** [comment]
We use this image internally in a number of different places, so introducing breaking changes to the default behavior is not tenable. However AFAIK we only use the generic secrets backend so `VAULT_USE_V1_API=secret` would be good enough I think.

**Comment by GeoffreyBooth** [comment]
Since you only published `:latest` earlier this week, presumably the places you’re using this internally are referencing a specific tag, like the `8fe0e9a0d488f863dfa5a4b58c36b7de7a2e682b` tag I see published? If so, merging this in and pushing a new `latest` or `master` shouldn’t break anything you’re running internally.

I feel like an image published for public use should follow the defaults. All anyone has to do to trigger the other behavior is set this environment variable on startup, for example in a `docker-compose.yml` file:

```yaml
  vault:
    image: quay.io/dollarshaveclub/vault-dev
    volumes:
      - ./secrets.json:/opt/secrets.json
    environment:
      VAULT_USE_V1_API: secret
    ports:
      - '8200:8200'
```

Or perhaps the image published for public use should be on the public Docker registry.

**Comment by bkeroackdsc** [comment]
We publish this repo and image as a courtesy to others that may find it useful, but I'm not willing to merge any PRs that could cause breakage for our internal systems. The condition for merging this PR avoiding incompatible behavior. Feel free to fork and publish the modified image yourself if you prefer.

Regardless, thank you for the contribution.

**Pull request closed without merging**
